# Generated by Django 6.0.2 on 2026-03-08 15:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='created_at', verbose_name='task title')),
                ('description', models.TextField(help_text='Описание задачи', verbose_name='task description')),
                ('status', models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Done', 'Done')], default='New', max_length=15, verbose_name='task status')),
                ('deadline', models.DateTimeField(help_text='Конечная дата выполнения', verbose_name='task deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='task created at')),
                ('categories', models.ManyToManyField(blank=True, related_name='tasks', to='my_app.category', verbose_name='task categories')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Subtask title')),
                ('description', models.TextField(help_text='описание подзадачи', validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(100)], verbose_name='subtask description')),
                ('status', models.CharField(choices=[('New', 'New'), ('In progress', 'In progress'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Done', 'Done')], default='New', max_length=15, verbose_name='subtask status')),
                ('deadline', models.DateTimeField(verbose_name='subtask deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='subtask created at')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subtasks', to='my_app.task', verbose_name='subtask task')),
            ],
        ),
    ]
